name: CI

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
      - README
  pull_request:
    branches:
      - '*'
    paths-ignore:
      - 'docs/**'
      - '**/*.md'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.9'
    - name: Setup Dependencies
      run: |
        go get github.com/daviddengcn/go-colortext
        go get github.com/subosito/gotenv
        go get golang.org/x/crypto/ssh/terminal
    - name: Build
      run: make build
    - name: Test
      run: make test
